### PR TITLE
Add analytics event tracking

### PR DESCRIPTION
**Pull request by pietschy**
Hi Jordan,

If you're interested I've added a the ability to fire a google analytics event when the form is successfully submitted (to track lead generation goals).  If you think it's useful feel free to include and let me know if you think anything can be added.

Cheers
Andrew

### CODE REVIEW

**Comment by pietschy** [comment]
Please note the pull request is a bit premature as I've only got this running on my local dev server so it's not properly tested yet.

**Comment by jordanlev** [comment]
Hi Andrew,
I appreciate you taking the time to submit this, but I'm not going to merge it into the master branch because I don't think it's a widely-used feature. Also, the template is designed to be easily customizable, so I actually think a more elegant solution to this would be to just paste in the GA code into the `else if (response.success) { ... }` block (like you have as part of your pull request.... but without all the extra variable definitions).

Thanks,
Jordan

**Comment by pietschy** [comment]
Hi Jordan, 

I needed at least the $formName variable so the event was unique for each form (otherwise all forms would track under a single event), that and if I put it all in the response handler I'd be mixing my models and views (c:  The $enableAnalyticsTracking was to be consistent with your $enablePlaceHolders variable, thus putting all configuration in the one place.

Also, the feature might not be widely used but it's critical if you're using adwords or doing SEO.  If you're not using events/pages to track goals (like lead generation) you're throwing money away.

But I'm fine if you don't want to include it.  Github rocks for that kind of thing.

Thanks!

**Comment by jordanlev** [comment]
Hi Andrew,
Thanks for the followup. I see what you mean, so I've added the $formName variable to the view. I don't think there's a need for the `$enableGoogleAnalytics` variable in the controller, because none of the controller logic needs to change if that's enabled (unlike the `$enablePlaceholders` variable, which changes input markup). Instead I've just added a note to the README explaining how to paste GA tracking code in the proper spot in `view.php`. So if you want to "enable" event tracking, you just paste in the code snippet -- no need for another controller variable to remember.

**Comment by pietschy** [comment]
Excellent, thanks for that.  I agree the enableGoogleAnalytics doesn't belong.  It also makes the template dependent on GA which would suck for you.

Thanks again.

**Pull request closed without merging**
